// Beyond.GEnums.SystemType
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum SystemType {
    Depot = 0,
    DelBuilding = 1,
    Drone = 5,
    Equip = 7,
    LevelBreak = 8,
    LevelUpgrade = 9,
    TeamSprint = 11,
    NormalSkill = 12,
    UltimateSkill = 13,
    MarkTarget = 14,
    ItemQuickStash = 16,
    FacBus = 101,
    FacBelt = 102,
    FacPort = 103,
    FacBridge = 111,
    FacConverger = 112,
    FacSplitter = 113,
    FacHubButton = 120,
    FacQuickBar = 121,
    WorldBuildOnPoleBase = 1000,
    WorldBuildOnMine = 1001,
}

// Beyond.GEnums.UnlockSystemType
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum UnlockSystemType {
    Map = 0,
    Inventory = 1,
    Watch = 2,
    ValuableDepot = 3,
    Shop = 4,
    Gacha = 51,
    Dungeon = 52,
    BlocMission = 53,
    Mail = 54,
    Wiki = 55,
    Prts = 56,
    SubmitEther = 57,
    Scan = 58,
    CharUi = 59,
    FacBuildingPin = 101,
    FacCraftPin = 102,
    FacMode = 103,
    FacTechTree = 104,
    FacOverview = 105,
    FacYieldStats = 106,
    FacConveyor = 107,
    FacTransferPort = 108,
    FacBridge = 109,
    FacSplitter = 110,
    FacMerger = 111,
    FacBus = 112,
    FacZone = 113,
    FacSystem = 114,
    ManualCraft = 201,
    ItemUse = 202,
    ItemQuickBar = 203,
    Weapon = 251,
    Equip = 252,
    NormalAttack = 301,
    NormalSkill = 302,
    UltimateSkill = 303,
    None = 10000000,
}

impl UnlockSystemType {
    // All systems that should be unlocked by default for a new player.
    pub fn default_unlocked() -> Vec<i32> {
        vec![
            Self::Map as i32,
            Self::Inventory as i32,
            Self::Watch as i32,
            Self::ValuableDepot as i32,
            Self::Shop as i32,
            Self::Dungeon as i32,
            Self::Mail as i32,
            Self::Wiki as i32,
            Self::Prts as i32,
            Self::SubmitEther as i32,
            Self::Scan as i32,
            Self::CharUi as i32,
            Self::ManualCraft as i32,
            Self::ItemUse as i32,
            Self::ItemQuickBar as i32,
            Self::Weapon as i32,
            Self::Equip as i32,
            Self::NormalAttack as i32,
            Self::NormalSkill as i32,
            Self::UltimateSkill as i32,
        ]
    }

    pub fn all() -> Vec<i32> {
        vec![
            Self::Map as i32,
            Self::Inventory as i32,
            Self::Watch as i32,
            Self::ValuableDepot as i32,
            Self::Shop as i32,
            Self::Gacha as i32,
            Self::Dungeon as i32,
            Self::BlocMission as i32,
            Self::Mail as i32,
            Self::Wiki as i32,
            Self::Prts as i32,
            Self::SubmitEther as i32,
            Self::Scan as i32,
            Self::CharUi as i32,
            Self::FacBuildingPin as i32,
            Self::FacCraftPin as i32,
            Self::FacMode as i32,
            Self::FacTechTree as i32,
            Self::FacOverview as i32,
            Self::FacYieldStats as i32,
            Self::FacConveyor as i32,
            Self::FacTransferPort as i32,
            Self::FacBridge as i32,
            Self::FacSplitter as i32,
            Self::FacMerger as i32,
            Self::FacBus as i32,
            Self::FacZone as i32,
            Self::FacSystem as i32,
            Self::ManualCraft as i32,
            Self::ItemUse as i32,
            Self::ItemQuickBar as i32,
            Self::Weapon as i32,
            Self::Equip as i32,
            Self::NormalAttack as i32,
            Self::NormalSkill as i32,
            Self::UltimateSkill as i32,
        ]
    }
}

// Beyond.GEnums.AttributeType
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum AttributeType {
    Level = 0,
    Hp = 1,
    Atk = 2,
    Def = 3,
    PhysicalResistance = 4,
    FireResistance = 5,
    PulseResistance = 6,
    CrystResistance = 7,
    Weight = 8,
    CriticalRate = 9,
    CriticalDamage = 10,
    Hatred = 11,
    NormalAttackRange = 12,
    MoveSpeedMultiplier = 13,
    TurnRateMultiplier = 14,
    AttackRate = 15,
    CooldownMultiplier = 16,
    SightRange = 17,
    FieldOfView = 18,
    DamageTakenScalar = 19,
    HpRecoveryPerSec = 20,
    HpRecoveryPerSecByMaxHpRatio = 21,
    MaxPoise = 22,
    PoiseRecTime = 23,
    MaxUltimateSp = 24,
    PoiseDamageResistScalar = 25,
    MaxAp = 26,
    ApRecoveryPerSec = 27,
    PoiseDamageTakenScalar = 28,
    PoiseProtectTime = 29,
    SpawnEnergyShardEfficiency = 30,
    PoiseZeroStun = 31,
    PoiseZeroDamageViaMaxHp = 32,
    Pen = 33,
    HealScalar = 34,
    HealTakenScalar = 35,
    PoiseRecTimeMultiplier = 36,
    PoiseBreakDamageIncrease = 37,
    PoiseBreakDamageTakenIncrease = 38,
    KnockDownTimeAddition = 39,
    FireEnergyShardProb = 40,
    PulseEnergyShardProb = 41,
    CrystEnergyShardProb = 42,
    FusionShardPreserveProb = 43,
    Enum = 44,
}

#[repr(i32)]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum ParamRealType {
    Invalid = 0,
    Bool = 1,
    BoolList = 2,
    Int = 3,
    IntList = 4,
    Float = 5,
    FloatList = 6,
    String = 7,
    StringList = 8,
    Path = 9,
    PathList = 10,
    Vector3 = 11,
    Vector3List = 12,
    EntityPtr = 13,
    EntityPtrList = 14,
    Tag = 15,
    TagList = 16,
    UInt = 17,
    UIntList = 18,
    FromContextCurrent = 19,
    FromContextMsg = 20,
    FromContextInteractive1 = 21,
    FromContextInteractive2 = 22,
    FromContextInteractive3 = 23,
    LevelScriptPtr = 24,
    LevelScriptPtrList = 25,
    UInt64 = 26,
    UInt64List = 27,
    LangKey = 28,
    LangKeyList = 29,
    Node = 30,
    NodeList = 31,
    Buff = 32,
    BuffList = 33,
    Bytes = 34,
    E_NUM = 35,
}

impl From<i32> for ParamRealType {
    fn from(value: i32) -> Self {
        match value {
            0 => ParamRealType::Invalid,
            1 => ParamRealType::Bool,
            2 => ParamRealType::BoolList,
            3 => ParamRealType::Int,
            4 => ParamRealType::IntList,
            5 => ParamRealType::Float,
            6 => ParamRealType::FloatList,
            7 => ParamRealType::String,
            8 => ParamRealType::StringList,
            9 => ParamRealType::Path,
            10 => ParamRealType::PathList,
            11 => ParamRealType::Vector3,
            12 => ParamRealType::Vector3List,
            13 => ParamRealType::EntityPtr,
            14 => ParamRealType::EntityPtrList,
            15 => ParamRealType::Tag,
            16 => ParamRealType::TagList,
            17 => ParamRealType::UInt,
            18 => ParamRealType::UIntList,
            19 => ParamRealType::FromContextCurrent,
            20 => ParamRealType::FromContextMsg,
            21 => ParamRealType::FromContextInteractive1,
            22 => ParamRealType::FromContextInteractive2,
            23 => ParamRealType::FromContextInteractive3,
            24 => ParamRealType::LevelScriptPtr,
            25 => ParamRealType::LevelScriptPtrList,
            26 => ParamRealType::UInt64,
            27 => ParamRealType::UInt64List,
            28 => ParamRealType::LangKey,
            29 => ParamRealType::LangKeyList,
            30 => ParamRealType::Node,
            31 => ParamRealType::NodeList,
            32 => ParamRealType::Buff,
            33 => ParamRealType::BuffList,
            34 => ParamRealType::Bytes,
            35 => ParamRealType::E_NUM,
            _ => ParamRealType::Invalid,
        }
    }
}

#[repr(i32)]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum ParamValueType {
    Invalid = 0,
    Bool = 1,
    BoolList = 2,
    Int = 3,
    IntList = 4,
    Float = 5,
    FloatList = 6,
    String = 7,
    StringList = 8,
}

impl From<i32> for ParamValueType {
    fn from(value: i32) -> Self {
        match value {
            0 => ParamValueType::Invalid,
            1 => ParamValueType::Bool,
            2 => ParamValueType::BoolList,
            3 => ParamValueType::Int,
            4 => ParamValueType::IntList,
            5 => ParamValueType::Float,
            6 => ParamValueType::FloatList,
            7 => ParamValueType::String,
            8 => ParamValueType::StringList,
            _ => ParamValueType::Invalid,
        }
    }
}
